### ISSUE TITLE
Archive historical repository

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/js-objects-this#13]
https://github.com/ga-wdi-boston/js-objects-this-08

**Comment by jrhorn424** [comment]
Transfer any issues from the historical repo.

**Comment by payne-chris-r** [comment]
Fixed with #19

**Comment by jrhorn424** [comment]
Thanks Chris, leaving this open since the old repository hasn't been migrated yet.

**Comment by gaand** [comment]
https://github.com/ga-wdi-boston-attic/js-objects-this-08

@jrhorn424 ☝️
