### ISSUE TITLE
Run a Grunt Nag (Archived from js-objects-this-08)

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/js-objects-this#19]
Run a Grunt Nag
MattB-GA-Boston opened this Issue on Jun 29, 2015

MattB-GA-Boston commented on Jun 29, 2015
Do it.

**Comment by jrhorn424** [comment]
I'm not sure this is actionable.

**Comment by gaand** [comment]
I concur.  One or both of  `grunt nag` and the atom linters should be regularly checked.

I am closing as Matt's proxy for this purpose.
